### ISSUE TITLE
closing properties box of file in shared folder crashes all instances of caja

### ISSUE THREAD

**Issue by bdantas** [mate-desktop-legacy-archive/mate-file-manager-share#3]
In a shared folder or dropbox folder, right-click on a file and choose "properties" (e.g., to check whether file is executable). When the properties box is closed, all instances of caja crash. The bug does not affect files in normal (non-shared, non-dropbox) folders.

According to Stefano, this is not a single bug (in caja) but two bugs (one in caja-dropbox and one in mate-file-manager-share).  The bug in caja-dropbox is reported here: https://github.com/mate-desktop/caja-dropbox/issues/4

**Comment by raveit65** [comment]
"mark as can be closed"
fixed with https://github.com/mate-desktop/mate-file-manager/commit/3512eb9905039f0dad597d7591a45b7fa763d2d7
