### ISSUE TITLE
Possible packaging issue

### ISSUE THREAD

**Issue by n32** [mate-desktop-legacy-archive/mate-file-manager-share#4]
How is this utility differentiated from "caja-share" referenced at
http://wiki.mate-desktop.org/applications:caja

In Ubuntu Mate neither "caja-share" or "mate-file-manager-share" was included with the default installation, and "mate-file-manager-share" is not available from the official repo.  In various forums I see that this omission has led some users on a wild goose chase, installing other Samba share apps which broke their Samba configuration.

**Comment by raveit65** [comment]
mate-file-manager-share was renamed to caja-share with 1.8.
Here in fedora i use this samba configuration for caja-share.
1. add those lines to global section in smb.conf
    usershare path = /var/lib/samba/usershare
    usershare max shares = 100
    usershare allow guests = yes
    usershare owner only = False
2. create /var/lib/samba/usershare
3.  add a group , ie. sambashare and use this for the new created folder
[root@mother rave]# ls -l /var/lib/samba/
drwxrwx--T  2 root sambashare   4096 26. Jan 19:43 usershare

Be aware of the stick-bit.
4. add the user to this group

That's it.
